### ISSUE TITLE
not displaying all 'My Markers'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xmindltd/xmind#165]
```
What steps will reproduce the problem?
1. Click: Show marker manager
2. create new marker group
3. Open local folder with png icons and select and import 50 for example

What is the expected output? What do you see instead?

I would expect to see all markers appearing in my markers tab. Instead, I
only see as much as it can be shown horizontally. This means 7 when having
it as a side pane or 25 when completely maximized.
I would expect to have a scroll bar to see all my markers for a group or
markers shown in multirow view

What version of the product are you using? On what operating system?

3.1.1 community, Opensuse 11.2 x64

Please provide any additional information below.

Otherwise this is a great product
```

Original issue reported on code.google.com by `sava.ra...@gmail.com` on 15 Apr 2010 at 8:41

**Comment by frankshaka** [comment]
1. We use the native toolbar control to display markers in Markers view, but on some Linux platforms the toolbar control does not _wrap_ into multiple lines like on Mac or Windows. This is a headache for cross-platform applications like us, and we're trying to figure out a way to workaround this.

2. It's not recommended to encapsulate large amount of markers into one marker group, because once you add one marker into a topic, the whole marker group will be embedded in the workbook for access on other machines. This would take more time when saving the XMind file.

**Comment by frankshaka** [comment]
Closing this issue as it is too old.
