### ISSUE TITLE
这个是怎么安装使用的？

### ISSUE THREAD

**Issue by zhuyoucai168** [xmindltd/xmind#305]
XMIND 这个开源项目和我们常规理解认识到的XMIND是一个还是同样功能的软件？

**Comment by frankshaka** [comment]
This is the same XMind as the one you know. This project contains all free part of the source code of XMind application. If you are evaluating the software, it's recommended to download a pre-built installation package from https://www.xmind.net/download/ and install it on a desktop computer. Otherwise, if you want to build the software using the source code, it needs some additional tools as described in [this wiki page](https://github.com/xmindltd/xmind/wiki/How-To-Build-Executable-RCP-Product).

I'm closing this issue now.
